name: Update StarzPlay Playlist
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        run: pip install requests
      - name: Run Script
        run: python update_playlist.py
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # سينشر كل الملفات بما فيها playlist.m3u
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
